### ISSUE TITLE
not working with reanimated2

### ISSUE THREAD

**Issue by sinclaireric** [Cnilton/react-native-floating-label-input#49]
when using reanimated2 the app crash,
**animated node with id 2 already**
 please make a version with reanimated2 dependency

**Comment by Cnilton** [comment]
Hi @sinclaireric, this weekend I'll look into it.

**Comment by sinclaireric** [comment]
thank , i'm waiting

**Comment by Cnilton** [comment]
Hi @sinclaireric, unfortunately, I couldn't find a way to make it work with both versions.. there are some steps in react-native-reanimated2 that do not allow the lib to use both versions, which is the babel.config.js where the plugin must be set. I'm sorry but I can't release as default the react-native-reanimated2 because it is still on alpha, and Software-Mansion even said other things may change during their release version.

**Comment by sinclaireric** [comment]
ok thank

**Comment by Ubax** [comment]
Hi @Cnilton 
Reanimated 2 is officially released now.
Could you create a release for it?

**Comment by Cnilton** [comment]
Hi guys, could you please try version 1.3.5 following the guide from README.md?

**Comment by Ubax** [comment]
HI @Cnilton 
It works in our project. 
Thanks
